#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Pre-process the the data generated by simulation for training.

@author: Matthijs de Jong
"""
# Standard library imports
import sys

# Project imports
from data_preprocessing_analysis.data_preprocessing import process_raw_data
import auxiliary.config


def main():
    # Overwrite config with command line arguments
    auxiliary.config.parse_args_overwrite_config(sys.argv[1:])

    # Preprocess data
    process_raw_data()


if __name__ == "__main__":
    main()
